[project]
name = "study-group-online-judge"
version = "0.1.0"
description = "An automated judging system facilitating scoring in Cerulean's study group."
readme = "README.md"
authors = [
    { name = "burnedinthesky", email = "ak@cerulean.works" }
]
requires-python = ">=3.14"
dependencies = [
    "datasets>=4.3,<5",
    "fastapi[standard]>=0.141.1",
    "pydantic>=2.13.5",
    "playwright>=1.58,<2",
    "python-dotenv>=1.2.3",
    "safetensors>=0.7,<1",
    "torch>=2.10,<2.12",
    "tqdm>=4.70.1",
    "transformers[torch]>=4.57,<5",
    "wandb>=0.30.0,<0.31",
]

[dependency-groups]
dev = [
    "pytest>=9,<10",
    "ruff>=0.16.8",
    "ty>=0.0.82",
]

[tool.uv.sources]
torch = [{ index = "pytorch-cpu", marker = "sys_platform == 'linux'" }]

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[project.scripts]
judge-server = "judge.main:app"

[build-system]
requires = ["uv_build>=0.12.16,<0.13.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = ["judge"]
